Repository terraform-ibm-modules/terraform-ibm-toolkit-vpc-subnets, pull requests merged in 2021-04, with the labels that each got.

#1 Adds initial version from terraform-ibm-vpc module
  .github/scripts/validate-deploy.sh
  .github/workflows/verify.yaml
  .gitignore
  README.md
  main.tf
  module.yaml
  outputs.tf
  provider.tf
  test/stages/stage1-cluster.tf
  test/stages/stage1-gateways.tf
  test/stages/stage1-namespaces.tf
  test/stages/stage1-olm.tf
  test/stages/stage1-resource-group.tf
  test/stages/stage1-vpc.tf
  test/stages/stage1b-capture-state.tf
  test/stages/stage2-mymodule.tf
  test/stages/stage2-subnets.tf
  test/stages/variables.tf
  variables.tf
  version.tf
Labels: feature, major

#2 Adds metadata entry for vpc_name variable
  module.yaml
  test/stages/stage1-vpc.tf
Labels: chore, patch

#3 Removes unneccesary vpc_id variable reference
  .github/workflows/publish-assets.yaml
  module.yaml
Labels: bug, patch

#4 Updates notify workflow
  .github/workflows/notify.yaml
Labels: chore, patch

#7 Adds support for passing ipv4 cidr values in for vpc
  .github/workflows/verify.yaml
  main.tf
  outputs.tf
  provider.tf
  test/stages/stage1-resource-group.tf
  test/stages/stage2-subnets.tf
  test/stages/variables.tf
  variables.tf
Labels: feature, minor

#5 Update dependencies and example
  README.md
Labels: chore, patch, skip ci

#9 Adds provision variable and logic to look up existing subnet
  main.tf
  outputs.tf
  variables.tf
Labels: feature, minor

#10 Fixes quotes used in ipv4_cidr_blocks variable description
  variables.tf
Labels: bug, patch, skip ci

#13 Adds logic to print subnet names to force sequencing
  main.tf
Labels: bug, patch

#15 Only returns subnets from data block of not provisioning
  main.tf
  outputs.tf
Labels: bug, patch
